# Generated by Django 5.2.1 on 2025-05-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PowerMasonProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='project',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Estimation',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
