# Generated by Django 5.2.1 on 2025-05-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PowerMasonProject', '0002_remove_cost_project_remove_estimation_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
