# Generated by Django 5.2.1 on 2025-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerMasonProject', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_report_month_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
