# Generated by Django 5.2.1 on 2025-05-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerMasonProject', '0004_project_progress_report_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Delayed', 'Delayed'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='OnGoing', max_length=20),
        ),
    ]
