# Generated by Django 5.2.1 on 2025-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerMasonProject', '0005_project_end_date_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delayed', 'Delayed'), ('Completed', 'Completed')], default='OnGoing', max_length=20),
        ),
    ]
